- name: Soap Request
  hosts: localhost
  connection: local
  vars:
    FILE: ./az_car_file/new-ping-car_0.0.42.car
  tasks:
    - name: render car file to variable
      set_fact:
        template_value: "{{ lookup('template', './az_car_file/new-ping-car_0.0.42.car') }}"

    - name: encode car file to base64
      copy:
        content: '{{ template_value | b64encode }}'
        dest: './carFileEncode.txt'

    - name: call soap service
      uri:
        url: 'https://192.168.56.1:9443/services/CarbonAppUploader.CarbonAppUploaderHttpsSoap12Endpoint'
        method: 'POST'
        body_format: raw
        user: admin
        password: admin
        force_basic_auth: yes
        validate_certs: false
        headers:
          Content-Type: text/xml; charset=utf-8
          # Content-Type: application/soap+xml; charset=utf-8;action="urn:updateLoggerData"
        body: "{{lookup('file','./carbonAppUploader.xml')}}"
        status_code: 202
        return_content: yes
      register: result
    - name: dump result
      debug:
        msg: '{{ result }}'
