- name: Soap Request
  hosts: localhost
  connection: local
  vars:
    car_name: new-ping-car_0.0.42.car
  tasks:
    - name: render car file to variable
      set_fact:
        car_value: "{{ lookup('template', './az_car_file/{{car_name}}') }}"

    - name: call soap service
      uri:
        url: https://192.168.56.1:9443/services/CarbonAppUploader.CarbonAppUploaderHttpsSoap11Endpoint
        method: 'POST'
        user: 'admin'
        password: 'admin'
        body: |
          <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:upl="http://upload.application.carbon.wso2.org" xmlns:xsd="http://upload.application.carbon.wso2.org/xsd">
             <soapenv:Header/>
              <soapenv:Body>
                  <upl:uploadApp>
                    <!--Zero or more repetitions:-->
                    <upl:fileItems>
                        <!--Optional:-->
                        <xsd:dataHandler>{{ car_value | b64encode }}</xsd:dataHandler>
                        <!--Optional:-->
                        <xsd:fileName>{{ car_name }}</xsd:fileName>
                        <!--Optional:-->
                        <xsd:fileType>jar</xsd:fileType>
                    </upl:fileItems>
                  </upl:uploadApp>
              </soapenv:Body>
          </soapenv:Envelope>
        force_basic_auth: true
        validate_certs: false
        headers:
          Content-Type: text/xml;charset=UTF-8
          SOAPAction: urn:uploadApp
        status_code: 200
      register: result
    - name: dump result
      debug:
        msg: '{{ result }}'
